[package]
name = "perl-xs"
version = "0.1.0"
authors = ["Vickenty Fesunov <kent@setattr.net>"]
license = "BSD-2-Clause"
edition = "2018"

[dependencies]
perl-sys = { git="https://github.com/vickenty/perl-sys" }